name: Build

on:
  pull_request:


permissions:
  contents: read


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'


jobs:
  build:
    name: Update calendars for tests
    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout last commit
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Setup ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run calendar updates
      run: |
        bundle exec ./app.rb

  auto-merge:
    name: Auto-merge Dependabot pull-requests
    runs-on: "ubuntu-latest"

    if: github.actor == 'dependabot[bot]'

    needs:
      - build

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Fetch Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Enable auto-merge for minor and patch updates
      if: |
        steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
        steps.metadata.outputs.update-type == 'version-update:semver-patch'
      run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
